## Cabecalho
def Lines():
    print("")
    print("0------------------------//------------------------0")
    print("")

def Head(days, money):
    print("0-- Reino -- Dia", days ,"-- Dinheiro", money, "-----------------0")

## Loading
def DrawLoading(x):
    if (x == 1):
        Lines()
        print("0                     Loading.                     0")
        Lines()
    elif (x == 2):
        Lines()
        print("0                     Loading..                    0")
        Lines()
    else:
        Lines()
        print("0                     Loading...                   0")
        Lines()
        
## Explorar   
def Explore():
    Lines()
    print("0                         N                        0")
    print("0                       ##|##                      0")
    print("0                     ####|####                    0")
    print("0                  O------+------L                 0")
    print("0                     ####|####                    0")
    print("0                       ##|##                      0")
    print("0                         S                        0")
    Lines()

## Torre de vigia
def Watcher():
    Lines()
    print("                 ______                             ")
    print("                /------\                            ")
    print("                |____o_|                            ")
    print("                |______|                            ")
    print("   / \ / \ / \  |  \/  |  / \  / \  / \  / \        ")
    print("   /|\ /|\ /|\  |  /\  |  /|\  /|\  /|\  /|\        ")
    print("   /|\ /|\ /|\  | /  \ |  /|\  /|\  /|\  /|\        ")
    print("    |   |   |   |/    \|   |    |    |    |         ")
    print("----------------------------------------------------")
    Lines()
    
## Backgounds do Castelo
def BackGround(x):
    if (x == 1):
        Lines()
        print("                                                    ")
        print("             <=^=^==^=^=>                           ")
        print("              | o    o |                            ")
        print("    |===|     |        | |===|                      ")
        print("    |   |================|   |                      ")
        print("  /\|   |        _       |   |/\/\/\/\/\/\          ")
        print(" /  | _ |       / \      | _ | /  \ \/  \ \         ")
        print(" |  |[X]|      |   |     |[X]| |  |  |  | |         ")
        print("----------------------------------------------------")
        Lines()
    elif (x == 2):
        Lines()
        print("                                                    ")
        print("             <=^=^==^=^=>                           ")
        print("              | o    o {                            ")
        print("    }===|     |        | }===|                      ")
        print("    |   |=-=|_;======-===|´  |                      ")
        print("  /\| `´|    `   _       |  `|/\/\/\/\/\/\          ")
        print(" /  | _ {       / \   `  | _ | /  \ \/  \ \         ")
        print(" |  |[X]|      |   |     |[X]| |  |  |  | |         ")
        print("----------------------------------------------------")
        Lines()
    elif (x == 3):
        Lines()
        print("                           (                        ")
        print("              /^=^==^=^=>   )                       ")
        print("              | o    o {   ())                      ")
        print("      _/|     |        | }===|                      ")
        print(" (   /  |=-=|_;======-===|´  |                      ")
        print(" () | `´|    `   _       }  `|/\/\/\/\/\            ")
        print(" / \| _ {       / \   `  } _ | /  \ \/  \           ")
        print(" |  |[X]|      |   }     |[X]| |  |  |  |           ")
        print("----------------------------------------------------")
        Lines()
    elif (x == 4):
        Lines()
        print("                 ()        (                        ")
        print("                  ()        )                       ")
        print("                  (()      ())                      ")
        print("      _/|         ( ))   }===|                      ")
        print(" (   /  |=-=|_;======-===|´  |                      ")
        print(" () | `´|    `   _       }  `|/\/\/\/\/\            ")
        print(" / \| _ {       / \   `  } _ | /  \ \/  \           ")
        print(" |  |[X]|      |   }     |[X]| |  |  |  |           ")
        print("----------------------------------------------------")
        Lines()

## Armaduras do Quartel
def DrawingQuarters(betterWeapon, betterArmor):
    if (betterWeapon == False and betterArmor == False):
        Lines()
        print("      .-                               .-.      ")
        print("    __|-|__                          __|-|__    ")
        print("   (_/'-'\_(    o                   (_/ -'\_)   ")
        print("   //\\___/\\\    |              |    //\\___/\\\ ")
        print("   ()/   \\()  0=#=           0=#=0  ()/   \\() ")
        print("    \:   :/     }              |     \:   :/    ")
        print("     (_I_)      |              }      (_I_)     ")
        print("      |:|       {              |       }:|      ")
        print("     /_:_\      '                     /_:_\     ")
        Lines()
    elif (betterWeapon == False and betterArmor == True):
        Lines()
        print("      .-.                              .-.      ")
        print("    __|-|__                          __|-|__    ")
        print("   (_/'-'\_)    o                   (_/'-'\_)   ")
        print("   //\\___/\\\    |              |    //\\___/\\\ ")
        print("   ()/   \\()  0=#=           0=#=0  ()/   \\() ")
        print("    \:   :/     }              |     \:   :/    ")
        print("     (_I_)      |              }      (_I_)     ")
        print("      |:|       {              |       |:|      ")
        print("     /_:_\      '                     /_:_\     ")
        Lines()
    elif (betterWeapon == True and betterArmor == False):
        Lines()
        print("      .-                               .-.      ")
        print("    __|-|__                          __|-|__    ")
        print("   (_/'-'\_(    o              o    (_/ -'\_)   ")
        print("   //\\___/\\\    |              |    //\\___/\\\ ")
        print("   ()/   \\()  0=#=0          0=#=0  ()/   \\() ")
        print("    \:   :/     |              |     \:   :/    ")
        print("     (_I_)      |              |      (_I_)     ")
        print("      |:|       |              |       }:|      ")
        print("     /_:_\      '              '      /_:_\     ")
        Lines()
    else:
        Lines()
        print("      .-.                              .-.      ")
        print("    __|-|__                          __|-|__    ")
        print("   (_/'-'\_)    o              o    (_/'-'\_)   ")
        print("   //\\___/\\\    |              |    //\\___/\\\ ")
        print("   ()/   \\()  0=#=0          0=#=0  ()/   \\() ")
        print("    \:   :/     |              |     \:   :/    ")
        print("     (_I_)      |              |      (_I_)     ")
        print("      |:|       |              |       |:|      ")
        print("     /_:_\      '              '      /_:_\     ")
        Lines()

## Horda de inimigos
def WaveDrawing(soldiers, betterWeapon):
    if (betterWeapon == True):
        if (soldiers < 10):
            Lines()
            print("                                                |   ")
            print("                                                |   ")
            print("                                                |   ")
            print("                                             |  |   ")
            print("                                           o |  |   ")
            print("                                           |/+ o|   ")
            print("                                           |    |   ")
            print("                                          / \   |   ")
            print("----------------------------------------------------")
            Lines()

        elif (soldiers < 20):
            Lines()
            print("                                                |   ")
            print("                                                |   ")
            print("                                                |   ")
            print("                                     |   |   |  |   ")
            print("                                   o | o | o |  |   ")
            print("                                   |/+ |/+ |/+ o|   ")
            print("                                   |   |   |    |   ")
            print("                                  / \ / \ / \   |   ")
            print("----------------------------------------------------")
            Lines()

        elif (soldiers < 40):
            Lines()
            print("                                                |   ")
            print("                                                |   ")
            print("                                                |   ")
            print("                             |   |   |   |   |  |   ")
            print("                           o | o | o | o | o |  |   ")
            print("                           |/+ |/+ |/+ |/+ |/+ o|   ")
            print("                           |   |   |   |   |    |   ")
            print("                          / \ / \ / \ / \ / \   |   ")
            print("----------------------------------------------------")
            Lines()

        elif (soldiers < 60):
            Lines()
            print("                                                |   ")
            print("                                                |   ")
            print("                                                |   ")
            print("                         |   |   |   |   |   |  |   ")
            print("                       o | o | o | o | o | o |  |   ")
            print("                       |/+ |/+ |/+ |/+ |/+ |/+ o|   ")
            print("                       |   |   |   |   |   |    |   ")
            print("                      / \ / \ / \ / \ / \ / \   |   ")
            print("----------------------------------------------------")
            Lines()

        elif (soldiers < 100):
            Lines()
            print("                                                |   ")
            print("                                                |   ")
            print("                                                |   ")
            print("                 |   |   |   |   |   |   |   |  |   ")
            print("               o | o | o | o | o | o | o | o |  |   ")
            print("               |/+ |/+ |/+ |/+ |/+ |/+ |/+ |/+ o|   ")
            print("               |   |   |   |   |   |   |   |    |   ")
            print("              / \ / \ / \ / \ / \ / \ / \ / \   |   ")
            print("----------------------------------------------------")
            Lines()

        elif (soldiers < 120):
            Lines()
            print("                                                |   ")
            print("                                                |   ")
            print("                                                |   ")
            print("         |   |   |   |   |   |   |   |   |   |  |   ")
            print("       o | o | o | o | o | o | o | o | o | o |  |   ")
            print("       |/+ |/+ |/+ |/+ |/+ |/+ |/+ |/+ |/+ |/+ o|   ")
            print("       |   |   |   |   |   |   |   |   |   |    |   ")
            print("      / \ / \ / \ / \ / \ / \ / \ / \ / \ / \   |   ")
            print("----------------------------------------------------")
            Lines()

        else:
            Lines()
            print("                                                |   ")
            print("                                                |   ")
            print("                                                |   ")
            print("     |   |   |   |   |   |   |   |   |   |   |  |   ")
            print("   o | o | o | o | o | o | o | o | o | o | o |  |   ")
            print("   |/+ |/+ |/+ |/+ |/+ |/+ |/+ |/+ |/+ |/+ |/+ o|   ")
            print("   |   |   |   |   |   |   |   |   |   |   |    |   ")
            print("  / \ / \ / \ / \ / \ / \ / \ / \ / \ / \ / \   |   ")
            print("----------------------------------------------------")
            Lines()
            
    elif (betterWeapon == False):
        if (soldiers < 10):
            Lines()
            print("                                                |   ")
            print("                                                |   ")
            print("                                                |   ")
            print("                                             |  |   ")
            print("                                           o }  |   ")
            print("                                           |/+ o|   ")
            print("                                           |    |   ")
            print("                                          / \   |   ")
            print("----------------------------------------------------")
            Lines()

        elif (soldiers < 20):
            Lines()
            print("                                                |   ")
            print("                                                |   ")
            print("                                                |   ")
            print("                                     }   |   |  |   ")
            print("                                   o | o } o }  |   ")
            print("                                   |/+ |/- |/+ o|   ")
            print("                                   |   |   |    |   ")
            print("                                  / \ / \ / \   |   ")
            print("----------------------------------------------------")
            Lines()

        elif (soldiers < 40):
            Lines()
            print("                                                |   ")
            print("                                                |   ")
            print("                                                |   ")
            print("                             |   {   }   |   |  |   ")
            print("                           o } o | o | o } o }  |   ")
            print("                           |/+ |/- |/+ |/- |/+ o|   ")
            print("                           |   |   |   |   |    |   ")
            print("                          / \ / \ / \ / \ / \   |   ")
            print("----------------------------------------------------")
            Lines()

        elif (soldiers < 60):
            Lines()
            print("                                                |   ")
            print("                                                |   ")
            print("                                                |   ")
            print("                         {   |   {   }   |   |  |   ")
            print("                       o | o } o | o | o } o }  |   ")
            print("                       |/+ |/+ |/- |/+ |/- |/+ o|   ")
            print("                       |   |   |   |   |   |    |   ")
            print("                      / \ / \ / \ / \ / \ / \   |   ")
            print("----------------------------------------------------")
            Lines()

        elif (soldiers < 100):
            Lines()
            print("                                                |   ")
            print("                                                |   ")
            print("                                                |   ")
            print("                 |   |   {   |   {   }   |   |  |   ")
            print("               o { o } o | o } o | o | o } o }  |   ")
            print("               |/+ |/- |/+ |/+ |/- |/+ |/- |/+ o|   ")
            print("               |   |   |   |   |   |   |   |    |   ")
            print("              / \ / \ / \ / \ / \ / \ / \ / \   |   ")
            print("----------------------------------------------------")
            Lines()

        elif (soldiers < 120):
            Lines()
            print("                                                |   ")
            print("                                                |   ")
            print("                                                |   ")
            print("         }   }   |   |   {   |   {   }   |   |  |   ")
            print("       o { o | o { o } o | o } o | o | o } o }  |   ")
            print("       |/+ |/+ |/+ |/- |/+ |/+ |/- |/+ |/- |/+ o|   ")
            print("       |   |   |   |   |   |   |   |   |   |    |   ")
            print("      / \ / \ / \ / \ / \ / \ / \ / \ / \ / \   |   ")
            print("----------------------------------------------------")
            Lines()

        else:
            Lines()
            print("                                                |   ")
            print("                                                |   ")
            print("                                                |   ")
            print("     |   {   |   }   }   |   {   {   }   |   |  |   ")
            print("   o } o | o { o { o | o } o | o | o | o } o }  |   ")
            print("   |/+ |/- |/+ |/+ |/- |/+ |/+ |/- |/+ |/- |/+ o|   ")
            print("   |   |   |   |   |   |   |   |   |   |   |    |   ")
            print("  / \ / \ / \ / \ / \ / \ / \ / \ / \ / \ / \   |   ")
            print("----------------------------------------------------")
            Lines()
